Sm/jwt hyperforce exception
salesforcecli/plugin-user pull request #805
Opened 2023-11-27 13:42 UTC by mshanemc

### What does this PR do?
When using hyperforce and JWT, you can't use `org create user` because (something about a user table replication in core that doesn't happen in hyperforce)

This now warns the user before trying to create a user that isn't auth-able. 

### What issues does this PR fix or reference?
[@W-14542428@](https://gus.lightning.force.com/a07EE00001f3jnGYAQ)

2023-11-27 18:27 UTC, jshackell-sfdc requested changes

2023-11-27 18:27 UTC, jshackell-sfdc commented on messages/create.md
> +- Auth to your DevHub with `org login web` or `org login sfdx-url`. Scratch orgs you create that way will work with `org create user`.
```suggestion
- Authorize your Dev Hub with  either the `org login web` or `org login sfdx-url` command.  You can then successfully use the `org create user` command on scratch orgs that you then create with your Dev Hub.
```

2023-12-04 21:30 UTC, shetzel approved these changes

2023-12-04 21:30 UTC, shetzel commented on src/commands/org/create/user.ts
> +    targetOrg.getField<string>(Org.Fields.CREATED_ORG_INSTANCE).endsWith('S')
So we can always trust that this will be accurate for all hyperforce instances?

2023-12-05 18:40 UTC, shetzel commented
QA:
Without changes:
```
sf org create user -o falcon-scratch2
Warning: The --target-dev-hub flag is deprecated and is no longer used by this command. The flag will be removed in API version 57.0 or later.
Error (1): Error authenticating with JWT.
Errors encountered:
user hasn't approved this consumer
```
With changes:
```
~/dev/salesforcecli/plugin-user/bin/dev.js org create user -o falcon-scratch2
Warning: The --target-dev-hub flag is deprecated and is no longer used by this command. The flag will be removed in API version 57.0 or later.
Error (1): This command doesn't work when authorizing an org using the JWT flow if the org is on Hyperforce.

Try this:

Authorize your Dev Hub with either the `org login web` or `org login sfdx-url` command. You can then successfully use the `org create user` command on scratch orgs that you create with your Dev Hub.
```

2023-12-05 19:20 UTC, merged